### PR TITLE
[bug fix] when doing chunk test should apply from minSize to (maxSize - 1)

### PR DESCRIPTION
**Pull request by Farley-Chen**
The old code test the chunk from minSize + 1 to maxSize.

I have read the implemention in other language.

Maybe there is a little bug.

We should test from minSize to maxSize - 1 to find the right chunk.

if it's not a bug, let me know please, thanks.

### CODE REVIEW

**Comment by Zabuzard** [comment]
Hey there, thanks for the contribution!

Have you tested it out? I was running the code on multiple GBs of real data and did not notice any issue.

**Comment by Farley-Chen** [comment]
@Zabuzard 
I test on a 1.9 GB file just now, chunk it and then combine.

The file's md5 remain unchanged.

I commit the pr not for the old code's running problem, but for the buffer range maybe not correct.

For the old code, you can see.
In FastCdcChunkerCore row 104, first you read minSize bytes

```java
long fingerprint = 0;
int i = minSize;
dataBuffer.write(stream.readNBytes(i));
```

then the for-loop
```java
	for (; i < normalSize; i++) {
                // here you read data first
		final int data = stream.read();
		if (data == -1) {
			throw new IllegalStateException(
					"Attempting to read a byte from the stream but the stream has ended");
		}
		dataBuffer.write(data);
		fingerprint = (fingerprint << 1) + gear[data];
		if ((fingerprint & maskSmall) == 0) {
			return dataBuffer.toByteArray();
		}
	}
```

In the loop, the code read data first, so there is minSize + 1 data in buffer.

Then the fingerprint is to be caculated.

So the range which chunk data caculated fingerprint is from minSize + 1 to n.

But I think maybe we need to caculated fingerprint from minSize to n - 1.

Because the max size do not need to caculated fingerprint.

English is not my first language (Maybe a little difficult to read, haha)

**Comment by Farley-Chen** [comment]
@Zabuzard 

I have reread the code of other language implement, maybe I have make a mistake.

I have a little question.

like this 

In FastCdcChunkerCore row 104, first we read minSize bytes

```java
long fingerprint = 0;
int i = minSize;
dataBuffer.write(stream.readNBytes(i));
```

then the for-loop

```java
for (; i < normalSize; i++) {
     // here you read data first
    final int data = stream.read();
    if (data == -1) {
        throw new IllegalStateException(
                "Attempting to read a byte from the stream but the stream has ended");
    }
    dataBuffer.write(data);
    fingerprint = (fingerprint << 1) + gear[data];
    if ((fingerprint & maskSmall) == 0) {
        return dataBuffer.toByteArray();
    }
}
```

In the loop, the code read data first, so there is minSize + 1 data in buffer.

Then the fingerprint is to be caculated.

So the range which chunk data caculated fingerprint is from minSize + 1 to n.

But why not caculated fingerprint from minSize to n - 1?

In my opinion, the min size should be caculated and the max size do not need to caculated fingerprint.

(If n - 1 is not desired, the n must be the desired)

The range to caculated is in the paper or not? (I have not read it yet)


Maybe I make a mistake thinking, because I found other language implements are the same range, but I do not why.


English is not my first language (Maybe a little difficult to read, haha)

**Comment by Zabuzard** [comment]
I am not sure which algorithm you are referring to specifically, that would have a different logic @Farley-Chen .
This is the pseudocode from the original paper, with cut-point skipping/normalized chunking around 8KB:

pseudo

You can see that the pseudo is pretty much identical with the code here, especially in regards to the `if` conditions and similar.

The fingerprint computation is done to eventually define a cut-point. But you want to skip the cut-point computation all together for the first `minSize` many bytes (2 KB in the pseudocode). So that all slices are at least `minSize` big always.
Then, between `minSize + 1` and `normalSize`, the regular cut-point computation with fingerprints is used. After reaching `normalSize`, you would swap the masks to make cut-point creation more likely. And after `maxSize`, you force a cut-point.

**Comment by Farley-Chen** [comment]
> I am not sure which algorithm you are referring to specifically, that would have a different logic @Farley-Chen . This is the pseudocode from the original paper, with cut-point skipping/normalized chunking around 8KB:
> 
> pseudo
> 
> You can see that the pseudo is pretty much identical with the code here, especially in regards to the `if` conditions and similar.
> 
> The fingerprint computation is done to eventually define a cut-point. But you want to skip the cut-point computation all together for the first `minSize` many bytes (2 KB in the pseudocode). So that all slices are at least `minSize` big always. Then, between `minSize + 1` and `normalSize`, the regular cut-point computation with fingerprints is used. After reaching `normalSize`, you would swap the masks to make cut-point creation more likely. And after `maxSize`, you force a cut-point.

@Zabuzard 

Thanks for replying me. I have a little doubt about the pseudo.

In the picture, `i` means the cutpoint and begin with `minSize`.

This means that in this loop `for; i < NormalSize; i++; do...`, the first time, `i` is just `MinSize`.

If the first time, `!(fp & MaskS)` return true(the condition aimed), the function will return just the same as `MinSize`.

It means cut range [0, minSize), include 0 not include minSize.

But in the code, the same loop `for (; i < normalSize; i++)`

```java
       for (; i < normalSize; i++) {
		final int data = stream.read();
		if (data == -1) {
			throw new IllegalStateException(
					"Attempting to read a byte from the stream but the stream has ended");
		}
               // hear we read data first, and then write it
		dataBuffer.write(data);
		fingerprint = (fingerprint << 1) + gear[data];
		if ((fingerprint & maskSmall) == 0) {
			return dataBuffer.toByteArray();
		}
	}
```
We read and write data first, whitch means that in the buffer we have chunk range [0, minSize], include 0 include minSize.

If the condition aimed, the buffer return with length `minSize + 1`, not the same as the pseudo.

I don't know if I make a mistake of the pseudo.

**Comment by Farley-Chen** [comment]
@Zabuzard 

Also, my code is wrong. I think maybe we can not use stream in this scene?

Or should we state the last data read from the stream in the iterator?

**Comment by Farley-Chen** [comment]
@Zabuzard 

The main problem is that, in pseudo, he test the data on `src[i]`

If ok, he returns `i`,

So data test is on offset `i`, but data cut range is [ lastOffset, i ), not include offset `i`.

In our code, we test data on `stream.read()`

If ok, we return `buffer` which contain the data we read.

Maybe not the same?

**Comment by Zabuzard** [comment]
Ah, now I get what you are trying to say. You might be on something here, but it needs verification instead of just assuming. This code is used by a few very big companies and we cannot just change something without being sure that its still correct.

**Pull request closed without merging**
